"""
Offline Website Generator

MyAgent V15.0.0
"""


def generate_file(filetype, project_name):

    if filetype == "html":
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{project_name}</title>
<link rel="stylesheet" href="style.css">
</head>

<body>

<header>
<h1>Welcome to {project_name}</h1>
<p>Powered by MyAgent V15</p>
</header>

<main>

<section>
<h2>About</h2>
<p>This website was generated locally by MyAgent.</p>
</section>

</main>

<script src="script.js"></script>

</body>
</html>
"""

    if filetype == "css":
        return """body{
font-family:Arial,sans-serif;
margin:0;
padding:0;
background:#f4f4f4;
color:#333;
}

header{
background:#2563eb;
color:white;
padding:40px;
text-align:center;
}

main{
padding:30px;
}

section{
background:white;
padding:20px;
border-radius:10px;
}
"""

    if filetype == "javascript":
        return """console.log("Website generated by MyAgent V15");"""

    return ""
