"""
Project Templates

MyAgent V13.3.0
"""

from pathlib import Path

PROJECTS = Path("Projects")


def create_flask(name):

    root = PROJECTS / name

    (root / "templates").mkdir(parents=True, exist_ok=True)
    (root / "static").mkdir(exist_ok=True)

    (root / "app.py").write_text(
        """from flask import Flask

app = Flask(__name__)

@app.route("/")
def home():
    return "Hello from MyAgent!"

if __name__ == "__main__":
    app.run(debug=True)
""",
        encoding="utf-8",
    )

    (root / "requirements.txt").write_text(
        "Flask\n",
        encoding="utf-8",
    )

    (root / "README.md").write_text(
        f"# {name}\n\nGenerated by MyAgent.\n",
        encoding="utf-8",
    )

    return str(root)


def create_python_cli(name):

    root = PROJECTS / name

    root.mkdir(parents=True, exist_ok=True)

    (root / "main.py").write_text(
        """def main():
    print("Hello from MyAgent!")

if __name__ == "__main__":
    main()
""",
        encoding="utf-8",
    )

    (root / "README.md").write_text(
        f"# {name}\n",
        encoding="utf-8",
    )

    return str(root)
